name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: git submodule update --init --recursive
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: jerbaroo 
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
      -A ghc.todolist-backend
      -A ghc.todolist-common
      -A ghc.todolist-frontend
      -A ghc.testing-backend
      -A ghc.testing-common
      -A ghc.testing-frontend
      -A ghc.telescope
      -A ghc.telescope-ds-file
      -A ghc.telescope-ds-reflex-dom
      -A ghc.telescope-ds-test
      -A ghc.telescope-ds-server
      -A ghc.telescope-ds-server-api
      -A ghc.telescope-ds-server-types
