name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: git submodule update --init --recursive
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: jerbaroo 
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A ghc.telescope -A ghc.telescope-ds-test
